name: vcare_flutter
description: "Vcare Flutter"
publish_to: "none"
version: 0.0.1
environment:
  sdk: ^3.5.2

dependencies:
  cupertino_icons: ^1.0.8
  chopper: ^8.0.3
  easy_avatar: ^3.0.0
  extended_image: ^8.3.0
  flutter:
    sdk: flutter
  flutter_datetime_picker_plus: ^2.2.0
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.8
  group_button: ^5.3.4
  intl: any
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  keyboard_avoider: ^0.2.0
  logging: ^1.3.0
  matertino_radio: ^1.0.5
  page_transition: ^2.1.0
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  sqfentity: ^2.5.0
dev_dependencies:
  build_runner: ^2.4.13
  build_verify: ^3.1.0
  chopper_generator: ^8.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pretty_dio_logger: ^1.3.1
  sqfentity_gen: ^2.5.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: HarmonyOS
      fonts:
        - asset: assets/fonts/HarmonyOS.ttf
          style: normal
flutter_intl:
  enabled: true