name: vcare_flutter
description: "Vcare Flutter"
publish_to: "none"
version: 0.0.1
environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl: any
  dio: ^5.7.0
  extended_image: ^8.3.0
  sqfentity: ^2.5.0
  sqfentity_gen: ^2.5.0
  flutter_datetime_picker_plus: ^2.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  pretty_dio_logger: ^1.3.1
  build_runner: ^2.4.13
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
#  fonts:
#    - family: HarmonyOS
#      fonts:
#        - asset: assets/fonts/HarmonyOS.ttf
#          style: normal
flutter_intl:
  enabled: true